### ISSUE TITLE
Multiple data columns

### ISSUE THREAD

**Issue by ViralBShah** [JuliaComputing/IndexedTables.jl#1]
@tanmaykm and I generated some data and loaded it up here.  It was pretty fun to use even in this early stage. One key question that kept coming was - why not have multiple data columns, like we have multiple indexes? 

Right now, one would have to create a new data type where each data column would we be a field, giving a row layout. While that is great in some cases, in other cases, in others, it is just simpler to have multiple columns.

**Comment by JeffBezanson** [comment]
Yes, I think this could be done assuming every column has data for every index. If some columns are missing data in some locations, you'd have to use Nullable or NullableArrays manually, but I think that gives a cleaner model.

**Comment by ViralBShah** [comment]
I just discussed this with @tanmaykm and we reached the same conclusion.

**Comment by JeffBezanson** [comment]
I think the right way to do this is to think of NDSparse as a pair of tables: one of indexes, one of values. That way the object that manages the struct-of-arrays or array-of-structs is de-coupled from NDSparse itself. The data part will behave like an array of structs, but might use e.g. StructsOfArrays.jl as the implementation. So the API will look like e.g. `filter(x->x.close > x.open, prices)`.
