### ISSUE TITLE
dropna doesn't work on Columns

### ISSUE THREAD

**Issue by piever** [JuliaComputing/IndexedTables.jl#102]
`dropna`  doesn't work when the input is of type Columns:

```julia
julia> c = Columns(rand(10));

julia> dropna(c)
ERROR: MethodError: no method matching subtable(::IndexedTables.Columns{Tuple{Float64},Tuple{Array{Float64,1}}}, ::Array{Int64,1})
Closest candidates are:
  subtable(::IndexedTables.NextTable, ::Any) at /Users/pietro/.julia/v0.6/IndexedTables/src/table.jl:330
  subtable(::IndexedTables.NDSparse, ::Any) at /Users/pietro/.julia/v0.6/IndexedTables/src/ndsparse.jl:567
Stacktrace:
 [1] dropna(::IndexedTables.Columns{Tuple{Float64},Tuple{Array{Float64,1}}}) at /Users/pietro/.julia/v0.6/IndexedTables/src/selection.jl:347

julia> dropna(table(c))
Table with 10 rows, 1 columns:
1
─────────
0.556384
0.244188
0.687944
0.452537
0.475721
0.189574
0.97688
0.714058
0.0153766
0.809821
```

which I think is an oversight, because there is a method explicitly for Columns in `dropna`:

```julia
julia> methods(dropna)
# 4 methods for generic function "dropna":
dropna(X::DataValues.DataValueArray{T,1} where T) in DataValues at /Users/pietro/.julia/v0.6/DataValues/src/array/primitives.jl:187
dropna(t::Union{IndexedTables.Columns, IndexedTables.NDSparse, IndexedTables.NextTable}) in IndexedTables at /Users/pietro/.julia/v0.6/IndexedTables/src/selection.jl:347
dropna(t::Union{IndexedTables.Columns, IndexedTables.NDSparse, IndexedTables.NextTable}, by) in IndexedTables at /Users/pietro/.julia/v0.6/IndexedTables/src/selection.jl:347
dropna(X::AbstractArray{T,1}) where T in DataValues at /Users/pietro/.julia/v0.6/DataValues/src/array/primitives.jl:176
```

**Comment by shashi** [comment]
Should I fix it by removing the method or by making this work? :-) there's the possibility of moving Columns out of this package. Its purpose is solely to behave like an array of tuples... Of course then `dropna` method could be kept in this package, but that's a bit of type piracy since neither Columns nor dropna would be defined in this package.

**Comment by piever** [comment]
I see the issue. If Columns is to be the "common ground" representation of a table (array of named tuples stored in an efficient way) then maybe it shouldn't have a `dropna` method, as `dropna` is tied to a different representation of missingness than what DataFrames uses. In any case this doesn't seem too annoying, as the following shouldn't give any overhead:

`dropna(table(c, copy = false)).columns`

**Comment by shashi** [comment]
Okay then I'm going to fix this by restricting dropna to Table.
