### ISSUE TITLE
Bad ordering of arguments in reduce method with initial value

### ISSUE THREAD

**Issue by piever** [JuliaComputing/IndexedTables.jl#158]
When trying to do the following:

`reduce(popcol, t, (:a, :b, :c))`

I accidentally ended up calling a specialized method for tables:

`reduce(f, t::Dataset, v0)`

However here my `t` is the initial value of the reduction, not the iterable (which instead is `(:a, :b, :c)` and I think we're overloading with the wrong signature. The Base method is `reduce(f, v0, iter)` where the second argument is the initial value, not the iterable. Should we deprecate `reduce(f, t::Dataset, v0)` in favor of `reduce(f, v0, t::Dataset)` ?

Happy to do a PR if we agree on the deprecation.

**Comment by joshday** [comment]
That seems reasonable to me.
