### ISSUE TITLE
Support for Julia 0.7/1.0 (i.e. NamedTuples in core) ?

### ISSUE THREAD

**Issue by sylvaticus** [JuliaComputing/IndexedTables.jl#186]
Hello, this package currently fails on Julia 0.7.
One motivation is that Julia 0.7 introduced NamedTuple in core, and hence to use the NamedTuples.jl implementation one has to use the full qualifying name `NamedTuples.NamedTuple`.

I did try to modify the code for taking care of that, but I still have an error that I don't understand:
```
WARNING: importing deprecated binding Base.Nullable into IndexedTables.
ERROR: LoadError: LoadError: TypeError: in Type{...} expression, expected UnionAll, got typeof(Base.Nullable)
```
and I wander if the package author want to switch to the core implementation of NamedTuples instead.

So, it's there any roadmap/plan to update this package to Julia 1.0 ?

**Comment by andreasnoack** [comment]
Please see https://github.com/JuliaComputing/IndexedTables.jl/pull/182
