### ISSUE TITLE
_default_type not defined

### ISSUE THREAD

**Issue by MikeInnes** [JuliaComputing/IndexedTables.jl#193]
Coming from [this line](https://github.com/JuliaComputing/IndexedTables.jl/blob/a222bef146b1a44ca79044cfcbbfeaa2b8c2df00/src/utils.jl#L252) when trying to do a join; I assume the fix is obvious to someone who knows what they're doing, but I can post a repro if needed.

**Comment by piever** [comment]
This only happens on Julia master. We should actually try to get rid of `_promote_op`...
