### ISSUE TITLE
no method matching pointer(::CategoricalString{UInt8}, ::Int64)

### ISSUE THREAD

**Issue by SimonDanisch** [JuliaComputing/IndexedTables.jl#206]
Currently tagged versions (also tried master of involved packages):
```Julia
using StructArrays, IndexedTables, RDatasets

iris = RDatasets.dataset("datasets", "iris")
itr = iris[:Species]
collect_columns(itr) # the error
# it seems the initializor for the following is at fault:
StructArrays.collect_structarray(itr, initializer = default_initializer)
```
If you change the `inititializer` to `StructArrays.default_initializer` it works - I'm not sure if it yields the correct result though :P

**Comment by piever** [comment]
This works fine for me on current master: can you try it again on IndexedTables master (a largish PR just got merged)?

**Comment by SimonDanisch** [comment]
True story! Thanks :)
