### ISSUE TITLE
swap order of dimensions?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaComputing/IndexedTables.jl#22]
It's a bit annoying that dimension 1 of an NDSparse corresponds to the *highest* dimension of the same data represented as an Array. This was done because it feels a bit more intuitive for the leftmost column to be the primary key, and because that's how lexicographic order is usually defined. But for harmony with other array types, we might want to give this up.

**Comment by ViralBShah** [comment]
I do like having the same abstractions, and my knowledge of other arrays just transferring over without further "thinking overhead".

**Comment by JeffBezanson** [comment]
I think I've decided against this; NDSparse just uses "row major" instead of "column major" order, and our array infrastructure increasingly supports arrays with different storage orders. Converting other N-d array types to NDSparse without permuting dimensions does not seem likely to be an important use case.
