### ISSUE TITLE
Tables of big objects takes very long / infinite time to display

### ISSUE THREAD

**Issue by piever** [JuliaComputing/IndexedTables.jl#231]
As a MWE, just evaluate this in the REPL or inline in Atom:

```julia
using IndexedTables
t = table((; x=rand(1_000_000)))
s = table((; a = [rows(t) for i in 1:1_000_000]))
```

The `show` method never manages to finish, even though building the table is relative cheap.

**Comment by shashi** [comment]
I guess we should call some variation of `show`/`showcompact` for the element types. But the answer to the question of which variation has eluded me.
