### ISSUE TITLE
Register and tag

### ISSUE THREAD

**Issue by davidanthoff** [JuliaComputing/IndexedTables.jl#25]
I'm supporting `NDSparse` data sources in [Query.jl](https://github.com/davidanthoff/Query.jl) now, and it would make things easier on my end if this package here was registered and tagged so that I can add it to the REQUIRE file of the tests.

**Comment by ViralBShah** [comment]
We may want to consider a newer name before registering.

**Comment by davidanthoff** [comment]
Bump, any chance this could be registered and tagged soon? It would make testing for [Query.jl](https://github.com/davidanthoff/Query.jl) a lot easier.

**Comment by ViralBShah** [comment]
Note the package name change. I believe there is going to be a huge amount of api changing going forward. @JeffBezanson @StefanKarpinski  should we at least tag a version now so that packages can depend on something in a stable way?

**Comment by davidanthoff** [comment]
Bump, any chance that this could be registered and tagged? I don't mind API churn, but not having it registered makes the whole CI testing from [Query.jl](https://github.com/davidanthoff/Query.jl) painful.

**Comment by ViralBShah** [comment]
@shashi can you look into tagging this right away if possible so that @davidanthoff can streamline his workflow?

**Comment by shashi** [comment]
Cool, I'll do it as soon as #35 is merged.

**Comment by shashi** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/8476

**Comment by ViralBShah** [comment]
Not merged yet.

**Comment by davidanthoff** [comment]
Done, yay!

**Comment by ViralBShah** [comment]
@davidanthoff Thanks for the patience!
