### ISSUE TITLE
separate `Columns`?

### ISSUE THREAD

**Issue by JeffBezanson** [JuliaComputing/IndexedTables.jl#28]
This is a pretty self-contained data type that implements struct-of-arrays storage. It's quite possible it should be its own package. If so, what should it be called?

**Comment by JeffreySarnoff** [comment]
Apparently, it is happiest naming equi-length vectors. The data type holds named sequence(s) that are each to other one-to-one and onto; and sometimes their sheafing is significant and other times not.  

  **flasket**
 
       Artfully woven, a flasket is a long shallow basket with two handles.
       It is used to collect, carry, share and consume favored nourishment.

**Comment by joshday** [comment]
This now exists as https://github.com/piever/StructArrays.jl
