### ISSUE TITLE
?NDSparse

### ISSUE THREAD

**Issue by JeffreySarnoff** [JuliaComputing/IndexedTables.jl#31]
Why not call it IndexedTable?

**Comment by JeffBezanson** [comment]
Yes, this needs a rename. I think `IndexedTable` is too long; maybe `ITable`?

**Comment by JeffreySarnoff** [comment]
To follow current practice, ITable is exported from the package ITables.jl.

**Comment by ViralBShah** [comment]
Another suggestion - IxTable if we don't want it to sound like Apple designed tables. :-)

**Comment by JeffreySarnoff** [comment]
(@ViralBShah  I had the same thought) IxTable looks like 1 x Table (or 9Table), InxTable? IxdTable?
@JeffBezanson I understand there is strong forward technology in/through/with this.  Part of adoption is clarity in communicating opportunity -- `IndexedTable` or `RefTable` etc are more easily grasped.

**Comment by JeffreySarnoff** [comment]
[a good solution is found](https://github.com/JuliaComputing/IndexedTables.jl/pull/35)
