### ISSUE TITLE
bug in indexing with `:, Date`

### ISSUE THREAD

**Issue by scls19fr** [JuliaComputing/IndexedTables.jl#42]
https://github.com/JuliaComputing/IndexedTables.jl#indexing

explains how to use indexing but this doc should be improved to show how to get temperatures of all cities at a given date

    hitemps[:, Date(2016,7,8)]

looks like a good idea but it raises

    ERROR: MethodError: no method matching start(::Date)

**Comment by JeffBezanson** [comment]
I'd say this should work, and this is a bug.
