### ISSUE TITLE
unique method

### ISSUE THREAD

**Issue by simonbyrne** [JuliaComputing/IndexedTables.jl#65]
It would be useful to define a `unique` method which drops repeated rows.

**Comment by shashi** [comment]
`aggregate((x,y)->x, t)`

**Comment by simonbyrne** [comment]
I meant unique based on index and data rows, e.g.
```
julia> t = IndexedTable(Columns(a=[1,1,1,2,2,2]), Columns(b=[1,1,2,1,1,2]))
a │ b
──┼──
1 │ 1
1 │ 1
1 │ 2
2 │ 1
2 │ 1
2 │ 2
```
then I want
```
IndexedTable(Columns(a=[1,1,2,2]), Columns(b=[1,2,1,2]))
```

**Comment by shashi** [comment]
I see, that's a special case then...

Another case where the pattern:
```julia
withrows(unique, a)
```
is useful. ([also here](https://github.com/JuliaComputing/IndexedTables.jl/issues/63#issuecomment-318087703))

**Comment by MaximilianJHuber** [comment]
How do I do this today?

**Comment by joshday** [comment]
One possible solution, since `unique` works with any iterator and returns something that satisfies the Tables.jl interface:

```julia
julia> t = table((a=[1,1,1,2,2,2], b=[1,1,2,1,1,2]))
Table with 6 rows, 2 columns:
a  b
────
1  1
1  1
1  2
2  1
2  1
2  2

julia> unique(t)
4-element Array{NamedTuple{(:a, :b),Tuple{Int64,Int64}},1}:
 (a = 1, b = 1)
 (a = 1, b = 2)
 (a = 2, b = 1)
 (a = 2, b = 2)

julia> table(ans)
Table with 4 rows, 2 columns:
a  b
────
1  1
1  2
2  1
2  2
```

**Comment by MaximilianJHuber** [comment]
Wow, that's great! Can be closed, I guess.

**Comment by piever** [comment]
Actually given that we can collect any iterator of `NamedTuples`, so it may be better to do `IterTools.` to avoid the intermediate allocation:

```julia
julia> t |> IterTools.distinct |> table
Table with 4 rows, 2 columns:
a  b
────
1  1
1  2
2  1
2  2
```
