### ISSUE TITLE
rename aggregate to reduce

### ISSUE THREAD

**Issue by simonbyrne** [JuliaComputing/IndexedTables.jl#75]
`reduce` seems like a more consistent choice of verbs.

**Comment by andyferris** [comment]
Interesting that I came across this one - I've been thinking about `aggregate` vs `reduce`.

It seems that some things that other environments call "aggregates" are a bit more general than our `mapreduce`. For instance C# has an aggregate that can perform a final operation on the output of a `mapreduce`, for instance an average will need to divide by the number of elements. Things like taking the mean of a column is relatively common in the data space... so I'm not sure how best to accommodate this.

**Comment by shashi** [comment]
I noticed your SAC.jl package calls this `groupreduce` - I like this name.

**Comment by davidanthoff** [comment]
In LINQ they just use ``GroupBy`` for both cases and differentiate by the arguments. But they of course can dispatch on the signature details of arguments that are functions, which makes that case pretty simple.

**Comment by andyferris** [comment]
Yeah, between it being difficult to distingish containers, scalars and callables in Julia, and the prior existence of `mapreduce`, it seemed to me that a seperate `groupreduce` might be appropriate. 

Also, to me the "by" in `GroupBy` seemed slightly redundant in Julia's verb-based function name scheme. 

Of course, if all these were lazy then we'd only need `group` and `reduce` (well, `reduce.(...)` in this case).

**Comment by joshday** [comment]
Looks like we went with `groupreduce` on this one.
