### ISSUE TITLE
Constructing an IndexedTables from an Array should keep the sparse nature of IndexedTables

### ISSUE THREAD

**Issue by scls19fr** [JuliaComputing/IndexedTables.jl#91]
Hello,

When creating an IndexTable from an Array, I haven't found (but maybe that's possible) to keep the sparse nature of IndexTables by filtering out values during construction

```julia
julia> using IndexedTables

julia> a = zeros(5, 4)
5×4 Array{Float64,2}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

julia> a[2, 3] = 2
2

julia> it = IndexedTable(a)
─────┬────
1  1 │ 0.0
1  2 │ 0.0
1  3 │ 0.0
1  4 │ 0.0
2  1 │ 0.0
2  2 │ 0.0
2  3 │ 2.0
2  4 │ 0.0
3  1 │ 0.0
3  2 │ 0.0
3  3 │ 0.0
3  4 │ 0.0
4  1 │ 0.0
4  2 │ 0.0
4  3 │ 0.0
4  4 │ 0.0
5  1 │ 0.0
5  2 │ 0.0
5  3 │ 0.0
5  4 │ 0.0

julia> length(it) == length(a)
true
```

maybe a keyword argument accepting an anonymous function that filter out some values could be defined

```julia
julia> IndexedTable(a, filter=x->x==0)
ERROR: MethodError: no method matching IndexedTables.IndexedTable(::Array{Float64,2}; filter=#1)
Closest candidates are:
  IndexedTables.IndexedTable(::Any; idxcols, datacols) at /home/scls/.julia/v0.6/IndexedTables/src/tabletraits.jl:12 got unsupported keyword argument "filter"
  IndexedTables.IndexedTable(::Any...; names, rest...) at /home/scls/.julia/v0.6/IndexedTables/src/IndexedTables.jl:71
  IndexedTables.IndexedTable(::C<:IndexedTables.Columns, ::AbstractArray{T,1}; agg, presorted, copy) where {T, C<:IndexedTables.Columns} at /home/scls/.julia/v0.6/IndexedTables/src/IndexedTables.jl:45 got unsupported keyword argument "filter"
Stacktrace:
 [1] (::Core.#kw#Type)(::Array{Any,1}, ::Type{IndexedTables.IndexedTable}, ::Array{Float64,2}) at ./<missing>:0

julia> length(it) == 1
false
```

Kind regards

**Comment by shashi** [comment]
Right now, NDSparse is not exactly an array because we throw KeyError instead of return a default value. So this conversion is correct, like it or not.

I'll open a new issue to track this.

**Comment by shashi** [comment]
closing in favor of #103

**Comment by scls19fr** [comment]
I think constructing an IndexedArray from an Array but filtering out some values doesn't imply the concept of default value. that's (in my mind) a different problem

**Comment by scls19fr** [comment]
default value can have some interest when converting IndexedArray to Array but anonymous function to filter out some values have interest when converting Array to IndexedArray

**Comment by shashi** [comment]
Right now, you can filter the NDSparse as a stop-gap. This makes a good case for supplying a filter function in the constructor. I'm willing to accept the change in a PR, and believe that figuring out #103 is the right way to forward.
